#pragma once
#include "geocaching/storage/checkpoint.h"
#include "geocaching/storage/transaction.h"

namespace geocaching::storage
{
// Internal RAM layout only, never a disk format. Caller provides two disjoint
// arenas, outside task stacks, and serializes access. Views expire on commit.
class LogicalState
{
  public:
    class View
    {
      public:
        size_t size() const { return count_; }
        bool next(size_t& cursor, MutationView& entry) const
        {
            entry = {};
            if (cursor >= used_ || used_ - cursor < 4) return false;
            const auto* p = data_ + cursor;
            const size_t key_size = p[1], value_size = (size_t(p[2]) << 8) | p[3];
            if (key_size + value_size > used_ - cursor - 4) return false;
            entry = {p[0], {p + 4, key_size}, {p + 4 + key_size, value_size}, false};
            cursor += 4 + key_size + value_size;
            return true;
        }
        bool find(uint8_t table, ByteView key, ByteView& value) const
        {
            value = {};
            if (!key.data || !key.size) return false;
            size_t cursor = 0;
            MutationView entry;
            while (next(cursor, entry))
                if (entry.table == table && entry.key.size == key.size && !std::memcmp(entry.key.data, key.data, key.size))
                {
                    value = entry.value;
                    return true;
                }
            return false;
        }

      private:
        friend class LogicalState;
        const uint8_t* data_ = nullptr;
        size_t used_ = 0, count_ = 0;
    };

    LogicalState(uint8_t* first, uint8_t* second, size_t capacity)
        : active_(first), spare_(second), capacity_(capacity) {}
    View view() const
    {
        View out;
        out.data_ = active_;
        out.used_ = used_;
        out.count_ = count_;
        return out;
    }

    bool beginSnapshot()
    {
        if (snapshot_active_ || prepared_ || !validArenas()) return false;
        snapshot_active_ = snapshot_valid_ = true;
        snapshot_used_ = snapshot_count_ = 0;
        snapshot_last_ = {};
        return true;
    }
    bool appendSnapshot(const MutationView* entries, size_t count)
    {
        if (!snapshot_active_ || !snapshot_valid_ || (!entries && count)) return false;
        for (size_t i = 0; i < count; ++i)
        {
            const auto& entry = entries[i];
            if (entry.erase || entry.table < 1 || entry.table > 13 || !entry.key.data || !entry.key.size || entry.key.size > 96 ||
                entry.value.size > 32768 || (entry.value.size && !entry.value.data) ||
                (snapshot_count_ && !checkpointKeyBefore(snapshot_last_, entry)))
                return snapshot_valid_ = false;
            const auto start = snapshot_used_;
            if (!appendEntry(entry, snapshot_used_, snapshot_count_)) return snapshot_valid_ = false;
            snapshot_last_ = {entry.table, {spare_ + start + 4, entry.key.size}, {}, false};
        }
        return true;
    }
    void discardSnapshot() { snapshot_active_ = snapshot_valid_ = false; }
    template <class Validate>
    bool commitSnapshot(Validate validate)
    {
        if (!snapshot_active_ || !snapshot_valid_) return false;
        View candidate;
        candidate.data_ = spare_;
        candidate.used_ = snapshot_used_;
        candidate.count_ = snapshot_count_;
        if (!validate(candidate)) return false;
        auto* previous = active_;
        active_ = spare_;
        spare_ = previous;
        used_ = snapshot_used_;
        count_ = snapshot_count_;
        discardSnapshot();
        return true;
    }

    // validate sees the entire candidate state, allowing table schemas and
    // cross-references to be checked together. On failure live state is intact.
    // Mutations and their bytes must not borrow the spare arena being written.
    template <class Validate>
    bool prepare(const MutationView* mutations, size_t count, Validate validate)
    {
        return prepareGenerated(
            mutations, count, count,
            [](uint8_t*, size_t, size_t&)
            { return false; },
            validate);
    }

    // Exactly one mutation may encode directly into its candidate value slot.
    // The callback is synchronous and may only borrow live-state/input bytes.
    // No generated bytes become visible unless validation and commit succeed.
    template <class Generate, class Validate>
    bool prepareGenerated(const MutationView* mutations, size_t count, size_t generated_index,
                          Generate generate, Validate validate)
    {
        if (snapshot_active_ || prepared_ || !validArenas() || !mutations || !count || count > 64) return false;
        if (generated_index > count || (generated_index < count &&
                                        (mutations[generated_index].erase || mutations[generated_index].value.size))) return false;
        for (size_t i = 0; i < count; ++i)
        {
            const auto& m = mutations[i];
            if (m.table < 1 || m.table > 13 || !m.key.data || !m.key.size || m.key.size > 96 ||
                m.value.size > 32768 || (m.value.size && !m.value.data) || (m.erase && m.value.size)) return false;
            for (size_t j = 0; j < i; ++j)
                if (sameKey(mutations[j], m)) return false;
        }
        size_t candidate_used = 0, candidate_count = 0;
        auto append = [&](const MutationView& entry)
        {
            if (generated_index < count && sameKey(entry, mutations[generated_index]))
                return appendGeneratedEntry(entry, candidate_used, candidate_count, generate);
            return appendEntry(entry, candidate_used, candidate_count);
        };
        const auto live = view();
        size_t cursor = 0;
        MutationView entry;
        while (live.next(cursor, entry))
        {
            const MutationView* replacement = &entry;
            for (size_t i = 0; i < count; ++i)
                if (sameKey(entry, mutations[i]))
                {
                    replacement = &mutations[i];
                    break;
                }
            if (!append(*replacement)) return false;
        }
        for (size_t i = 0; i < count; ++i)
        {
            ByteView prior;
            if (!live.find(mutations[i].table, mutations[i].key, prior) && !append(mutations[i])) return false;
        }
        View candidate;
        candidate.data_ = spare_;
        candidate.used_ = candidate_used;
        candidate.count_ = candidate_count;
        if (!validate(candidate)) return false;
        prepared_used_ = candidate_used;
        prepared_count_ = candidate_count;
        prepared_ = true;
        return true;
    }

    // Transient scratch only before preparing a candidate. Never retain the
    // pointer across this call, perform I/O, or reenter this state owner.
    template <class Work>
    bool withScratch(Work work)
    {
        if (snapshot_active_ || prepared_ || !validArenas()) return false;
        work(spare_, capacity_);
        return true;
    }

    View preparedView() const
    {
        View out;
        if (prepared_)
        {
            out.data_ = spare_;
            out.used_ = prepared_used_;
            out.count_ = prepared_count_;
        }
        return out;
    }
    bool commitPrepared()
    {
        if (!prepared_) return false;
        auto* previous = active_;
        active_ = spare_;
        spare_ = previous;
        used_ = prepared_used_;
        count_ = prepared_count_;
        discardPrepared();
        return true;
    }
    void discardPrepared()
    {
        prepared_ = false;
        prepared_used_ = prepared_count_ = 0;
    }

    // In-memory callers share the same staging implementation. Device storage
    // calls prepare, then commits only after incremental durable verification.
    template <class Validate>
    bool apply(const MutationView* mutations, size_t count, Validate validate)
    {
        return prepare(mutations, count, validate) && commitPrepared();
    }

  private:
    bool validArenas() const
    {
        if (!active_ || !spare_ || !capacity_) return false;
        const auto a = reinterpret_cast<uintptr_t>(active_), b = reinterpret_cast<uintptr_t>(spare_);
        return (a <= b ? b - a : a - b) >= capacity_;
    }
    template <class Generate>
    bool appendGeneratedEntry(const MutationView& entry, size_t& used, size_t& count, Generate generate)
    {
        if (entry.erase) return true;
        const size_t prefix = 4 + entry.key.size;
        if (prefix > capacity_ - used) return false;
        auto* p = spare_ + used;
        const size_t available = capacity_ - used - prefix;
        const size_t limit = available < 32768 ? available : 32768;
        size_t size = 0;
        if (!generate(p + prefix, limit, size) || size > limit) return false;
        p[0] = entry.table;
        p[1] = static_cast<uint8_t>(entry.key.size);
        p[2] = static_cast<uint8_t>(size >> 8);
        p[3] = static_cast<uint8_t>(size);
        std::memcpy(p + 4, entry.key.data, entry.key.size);
        used += prefix + size;
        ++count;
        return true;
    }
    bool appendEntry(const MutationView& entry, size_t& used, size_t& count)
    {
        return appendGeneratedEntry(entry, used, count, [&](uint8_t* output, size_t capacity, size_t& written)
                                    {
            if (entry.value.size > capacity) return false;
            if (entry.value.size) std::memcpy(output, entry.value.data, entry.value.size);
            written = entry.value.size;
            return true; });
    }
    static bool sameKey(const MutationView& a, const MutationView& b)
    {
        return a.table == b.table && a.key.size == b.key.size && !std::memcmp(a.key.data, b.key.data, a.key.size);
    }
    uint8_t* active_;
    uint8_t* spare_;
    size_t capacity_, used_ = 0, count_ = 0;
    size_t snapshot_used_ = 0, snapshot_count_ = 0;
    MutationView snapshot_last_;
    bool snapshot_active_ = false, snapshot_valid_ = false;
    size_t prepared_used_ = 0, prepared_count_ = 0;
    bool prepared_ = false;
};
} // namespace geocaching::storage
