#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
INVENTORY = "docs/audits/LEGACY_COMPAT_TEMP_SURFACE_INVENTORY.md"
SCAN = "docs/audits/LEGACY_COMPAT_TEMP_SURFACE_SCAN.md"

REQUIRED_CATEGORIES = [
    "root legacy source roots",
    "compatibility shims",
    "deprecated aliases",
    "transitional descriptors",
    "fallback-only paths",
    "archive-only roots",
    "legacy build entries",
    "old build entrypoints",
    "legacy app shells",
    "adapter / bridge / facade layers",
    "probe / smoke-only runtime",
    "historical debt docs",
    "legacy-governing checkers",
    "legacy/transitional/compatibility/shim/fallback names",
]

REQUIRED_SURFACES = [
    "root legacy/",
    "legacy/app_implementations/esp_idf",
    "legacy/app_implementations/esp_pio",
    "legacy/app_implementations/gat562_mesh_evb_pro",
    "legacy/app_implementations/linux_rpi",
    "legacy/app_implementations/linux_sim",
    "legacy/app_implementations/linux_uconsole",
    "legacy/app_implementations/linux_unoq",
    "esp_idf_legacy_implementation_adapter",
    "nrf52_pio_legacy_implementation_adapter",
    "linux_sim_legacy_implementation_adapter",
    "uconsole_legacy_implementation_adapter",
    "linux_sim_legacy_source_descriptor",
    "linux_uconsole_gtk_legacy_source_descriptor",
    "ui_shared compatibility shims",
    "LegacyChatDeliveryActionBridge",
    "LegacyChatDeliveryEventBridge",
    "LegacyKeyVerificationSource",
    "LegacyKeyVerificationActionSink",
    "LegacyKeyVerificationSession",
    "LegacyMapOverlaySource",
    "LinuxSim hardcoded runtime routing",
    "GTK hardcoded page registry",
    "LVGL hardcoded menu/page creation",
    "legacy/app_implementations/linux_sim/archive",
    "legacy/app_implementations/linux_uconsole/archive",
    "legacy build CMake and library manifests",
    "legacy app shell roots",
    "adapter / bridge / facade naming surface",
    "probe and smoke runtime surface",
    "legacy-governing checker surface",
]

REQUIRED_FIELDS = [
    "Category:",
    "Current location:",
    "Current callers:",
    "Current responsibility:",
    "Final owner:",
    "Disposition:",
    "Delete condition:",
    "Risk:",
]

ALLOWED_DISPOSITIONS = [
    "Must Delete",
    "Must Rename",
    "Must Migrate",
    "Deleted",
    "Keep as Final Adapter",
    "Keep as Deprecated Alias Temporarily",
    "Test-only / Smoke-only",
]


def read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8", errors="ignore")


def require_file(rel: str, failures: list[str]) -> None:
    if not (ROOT / rel).is_file():
        failures.append(f"missing required file: {rel}")


def surface_blocks(text: str) -> list[tuple[str, str]]:
    matches = list(re.finditer(r"^## Surface: (.+)$", text, flags=re.MULTILINE))
    blocks: list[tuple[str, str]] = []
    for index, match in enumerate(matches):
        start = match.start()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        blocks.append((match.group(1).strip(), text[start:end]))
    return blocks


def check_inventory_shape(text: str, failures: list[str]) -> None:
    lower = text.lower()
    for category in REQUIRED_CATEGORIES:
        if category.lower() not in lower:
            failures.append(f"{INVENTORY} missing category: {category}")

    for surface in REQUIRED_SURFACES:
        if surface not in text:
            failures.append(f"{INVENTORY} missing required surface/token: {surface}")

    blocks = surface_blocks(text)
    if len(blocks) < len(REQUIRED_SURFACES):
        failures.append(
            f"{INVENTORY} has {len(blocks)} surface blocks; expected at least {len(REQUIRED_SURFACES)}"
        )

    for surface_name, block in blocks:
        for field in REQUIRED_FIELDS:
            if field not in block:
                failures.append(f"surface '{surface_name}' missing field: {field}")
        if not any(disposition in block for disposition in ALLOWED_DISPOSITIONS):
            failures.append(
                f"surface '{surface_name}' missing allowed disposition value"
            )
        for field in ["Final owner:", "Disposition:", "Delete condition:"]:
            pattern = re.compile(rf"{re.escape(field)}\s*\n-\s*(.+)")
            match = pattern.search(block)
            if not match or not match.group(1).strip():
                failures.append(f"surface '{surface_name}' has empty {field}")

    if "TBD" in text:
        for line_no, line in enumerate(text.splitlines(), start=1):
            if "TBD" in line and "owner" not in line.lower():
                failures.append(f"{INVENTORY}:{line_no} contains TBD without owner: {line}")


def check_scan_shape(text: str, failures: list[str]) -> None:
    for token in [
        "Generated by `tools/architecture/scan_legacy_compat_temp_surfaces.py`",
        "## Keyword Counts",
        "## Matched Paths",
        "`legacy`",
        "`compatibility`",
        "`fallback`",
        "`adapter`",
        "`probe`",
        "`smoke`",
    ]:
        if token not in text:
            failures.append(f"{SCAN} missing token: {token}")


def main() -> int:
    failures: list[str] = []
    require_file(INVENTORY, failures)
    require_file(SCAN, failures)

    if (ROOT / INVENTORY).is_file():
        check_inventory_shape(read(INVENTORY), failures)
    if (ROOT / SCAN).is_file():
        check_scan_shape(read(SCAN), failures)

    if failures:
        for failure in failures:
            print(f"[legacy-compat-temp-inventory] {failure}")
        return 1

    print("[legacy-compat-temp-inventory] OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
