#!/usr/bin/env python3
from __future__ import annotations

import subprocess
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "docs/audits/LEGACY_COMPAT_TEMP_SURFACE_SCAN.md"

KEYWORDS = [
    "legacy",
    "compat",
    "compatibility",
    "transitional",
    "temporary",
    "fallback",
    "shim",
    "deprecated",
    "archive-only",
    "adapter",
    "bridge",
    "probe",
    "smoke",
]

TEXT_SUFFIXES = {
    ".c",
    ".cc",
    ".cpp",
    ".cxx",
    ".h",
    ".hpp",
    ".cmake",
    ".ini",
    ".json",
    ".md",
    ".py",
    ".txt",
    ".yaml",
    ".yml",
}

EXCLUDED_PREFIXES = (
    "third_party/",
    "site/assets/",
    "docs/images/",
    "docs/EnergySweep/",
)

EXCLUDED_PARTS = {
    ".git",
    ".vs",
    ".vscode",
    "build",
    "build.tab5",
    "builds-out",
    "cmake-build-debug",
    "cmake-build-release",
    "_deps",
}

EXCLUDED_FILES = {
    "docs/audits/LEGACY_COMPAT_TEMP_SURFACE_SCAN.md",
}


@dataclass
class Match:
    keyword: str
    path: str
    line: int
    text: str


def git_files() -> list[str]:
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=ROOT,
        check=True,
        text=True,
        encoding="utf-8",
        errors="ignore",
        capture_output=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def should_scan(rel: str) -> bool:
    if rel in EXCLUDED_FILES:
        return False
    if rel.startswith(EXCLUDED_PREFIXES):
        return False
    path = Path(rel)
    if set(path.parts).intersection(EXCLUDED_PARTS):
        return False
    return path.suffix.lower() in TEXT_SUFFIXES


def scan() -> list[Match]:
    matches: list[Match] = []
    lowered_keywords = [(keyword, keyword.lower()) for keyword in KEYWORDS]
    for rel in git_files():
        if not should_scan(rel):
            continue
        path = ROOT / rel
        if not path.exists():
            continue
        try:
            lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
        except OSError:
            continue
        rel_posix = rel.replace("\\", "/")
        rel_lower = rel_posix.lower()
        path_keywords = [
            keyword for keyword, lowered in lowered_keywords if lowered in rel_lower
        ]
        for keyword in path_keywords:
            matches.append(Match(keyword, rel_posix, 0, "(path match)"))
        for line_no, line in enumerate(lines, start=1):
            lowered_line = line.lower()
            for keyword, lowered in lowered_keywords:
                if lowered in lowered_line:
                    matches.append(
                        Match(keyword, rel_posix, line_no, line.strip()[:180].strip())
                    )
    return matches


def render(matches: list[Match]) -> str:
    by_keyword: dict[str, list[Match]] = defaultdict(list)
    by_path: dict[str, set[str]] = defaultdict(set)
    for match in matches:
        by_keyword[match.keyword].append(match)
        by_path[match.path].add(match.keyword)

    lines: list[str] = [
        "# Legacy / Compatibility / Temporary Surface Scan",
        "",
        "Generated by `tools/architecture/scan_legacy_compat_temp_surfaces.py`.",
        "",
        "This scan is discovery input only. It is not a disposition decision and",
        "must be interpreted through `LEGACY_COMPAT_TEMP_SURFACE_INVENTORY.md`.",
        "",
        "## Keyword Counts",
        "",
        "| Keyword | Matches | Paths |",
        "| --- | ---: | ---: |",
    ]

    for keyword in KEYWORDS:
        keyword_matches = by_keyword.get(keyword, [])
        paths = {match.path for match in keyword_matches}
        lines.append(f"| `{keyword}` | {len(keyword_matches)} | {len(paths)} |")

    lines.extend(
        [
            "",
            "## Matched Paths",
            "",
            "| Path | Keywords |",
            "| --- | --- |",
        ]
    )
    for path in sorted(by_path):
        keywords = ", ".join(f"`{keyword}`" for keyword in sorted(by_path[path]))
        lines.append(f"| `{path}` | {keywords} |")

    lines.extend(["", "## Sample Matches By Keyword", ""])
    for keyword in KEYWORDS:
        lines.extend([f"### `{keyword}`", ""])
        for match in by_keyword.get(keyword, [])[:60]:
            if match.line == 0:
                lines.append(f"- `{match.path}`: path match")
            else:
                lines.append(f"- `{match.path}:{match.line}`: {match.text}")
        if len(by_keyword.get(keyword, [])) > 60:
            remaining = len(by_keyword[keyword]) - 60
            lines.append(f"- ... {remaining} additional matches omitted")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    matches = scan()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(matches), encoding="utf-8")
    print(f"[legacy-compat-temp-scan] wrote {OUTPUT.relative_to(ROOT).as_posix()}")
    print(f"[legacy-compat-temp-scan] matches: {len(matches)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
