#pragma once

#include <cstddef>
#include <cstdint>

namespace ui::theme
{

enum class ColorSlot : std::uint8_t
{
    PageBg = 0,
    SurfacePrimary,
    SurfaceSecondary,
    ChromeTopBar,
    OverlayScrim,
    BorderDefault,
    BorderStrong,
    SeparatorDefault,
    TextPrimary,
    TextMuted,
    TextInverse,
    AccentPrimary,
    AccentStrong,
    StateOk,
    StateInfo,
    StateWarn,
    StateError,
    MapBackground,
    MapRoute,
    MapTrack,
    MapMarkerBorder,
    MapSignalLabelBg,
    MapNodeMarker,
    MapSelfMarker,
    MapLink,
    MapReadoutId,
    MapReadoutLon,
    MapReadoutLat,
    MapReadoutDistance,
    MapReadoutProtocol,
    MapReadoutRssi,
    MapReadoutSnr,
    MapReadoutSeen,
    MapReadoutZoom,
    TeamMember0,
    TeamMember1,
    TeamMember2,
    TeamMember3,
    GnssSystemGps,
    GnssSystemGln,
    GnssSystemGal,
    GnssSystemBd,
    GnssSnrGood,
    GnssSnrFair,
    GnssSnrWeak,
    GnssSnrNotUsed,
    GnssSnrInView,
    SstvMeterMid,
    Count,
};

enum class AssetSlot : std::uint8_t
{
    BootLogo = 0,
    NotificationAlert,
    StatusRoute,
    StatusTracker,
    StatusGps,
    StatusWifi,
    StatusTeam,
    StatusMessage,
    StatusBle,
    MenuAppChat,
    MenuAppMap,
    MenuAppSkyPlot,
    MenuAppContacts,
    MenuAppEnergySweep,
    MenuAppTeam,
    MenuAppTracker,
    MenuAppPcLink,
    MenuAppSstv,
    MenuAppSettings,
    MenuAppExtensions,
    MenuAppUsb,
    MenuAppWalkieTalkie,
    MapSelfMarker,
    TeamLocationAreaCleared,
    TeamLocationBaseCamp,
    TeamLocationGoodFind,
    TeamLocationRally,
    TeamLocationSos,
    Count,
};

enum class ComponentSlot : std::uint8_t
{
    TopBarContainer = 0,
    TopBarBackButton,
    TopBarTitleLabel,
    TopBarRightLabel,
    DirectoryBrowserSelectorPanel,
    DirectoryBrowserContentPanel,
    DirectoryBrowserSelectorButton,
    DirectoryBrowserListItem,
    InfoCardBase,
    InfoCardHeader,
    BusyOverlayPanel,
    BusyOverlayProgressBar,
    NotificationBanner,
    ModalScrim,
    ModalWindow,
    MenuAppButton,
    MenuAppLabel,
    MenuBottomChipNode,
    MenuBottomChipRam,
    MenuBottomChipPsram,
    MenuDashboardAppGrid,
    MenuDashboardBottomChips,
    BootSplashRoot,
    BootSplashLog,
    WatchFaceRoot,
    WatchFacePrimaryRegion,
    WatchFaceNodeId,
    WatchFaceBattery,
    WatchFaceClockHour,
    WatchFaceClockMinute,
    WatchFaceClockSeparator,
    WatchFaceDate,
    ChatConversationRoot,
    ChatConversationThreadRegion,
    ChatConversationActionBar,
    ChatBubbleSelf,
    ChatBubblePeer,
    ChatBubbleText,
    ChatBubbleTime,
    ChatBubbleStatus,
    ChatComposeRoot,
    ChatComposeContentRegion,
    ChatComposeEditor,
    ChatComposeActionBar,
    MapFocusRoot,
    MapFocusPrimaryOverlay,
    MapFocusSecondaryOverlay,
    MapInfoPanel,
    MapControlButton,
    MapLayerPopupWindow,
    GpsIndicatorLabel,
    GpsLoadingBox,
    GpsLoadingLabel,
    GpsToastBox,
    GpsToastLabel,
    GpsZoomWindow,
    GpsZoomTitleBar,
    GpsZoomTitleLabel,
    GpsZoomValueLabel,
    GpsZoomRoller,
    InstrumentPanelRoot,
    InstrumentPanelBody,
    InstrumentPanelCanvasRegion,
    InstrumentPanelLegendRegion,
    ServicePanelRoot,
    ServicePanelBody,
    ServicePanelPrimaryPanel,
    ServicePanelFooterActions,
    TeamMemberChip,
    GnssSkyPanel,
    GnssStatusPanel,
    GnssStatusHeader,
    GnssTableHeader,
    GnssTableRow,
    GnssStatusToggle,
    GnssSatelliteUseTag,
    SstvImagePanel,
    SstvProgressBar,
    SstvMeterBox,
    ActionButtonPrimary,
    ActionButtonSecondary,
    Count,
};

const char* color_slot_id(ColorSlot slot);
bool color_slot_from_id(const char* slot_id, ColorSlot& out_slot);
std::size_t color_slot_count();

const char* asset_slot_id(AssetSlot slot);
bool asset_slot_from_id(const char* slot_id, AssetSlot& out_slot);
std::size_t asset_slot_count();

const char* component_slot_id(ComponentSlot slot);
bool component_slot_from_id(const char* slot_id, ComponentSlot& out_slot);
std::size_t component_slot_count();

} // namespace ui::theme
